### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by tommoor** [enzoferey/slate-instant-replace#9] opened 2019-12-05 03:45 UTC
It looks like this plugin doesn't work with server side rendering, it would be great to get a check for the existence of `window` before using it – likely just a code compilation setting?

https://github.com/outline/rich-markdown-editor/issues/133

**Comment by enzoferey** [comment] 2019-12-05 08:15
Hi @tommoor ! It looks like indeed a build issue because I don't reference the `window` object in the code at all. I will have a look at it during the day 👍 

P.S: I would appreciate you could have a look at https://github.com/tommoor/react-emoji-render/pull/41 😉

**Comment by enzoferey** [comment] 2019-12-05 21:25
(should be) fixed via https://github.com/enzoferey/slate-instant-replace/pull/10.

SSR is always a pain for libraries building, I have never done and you don't find much resources, but it looks like it's working 👍 

I will keep the issue open until confirmed at https://github.com/outline/rich-markdown-editor/issues/133.

**Comment by enzoferey** [comment] 2019-12-06 08:23
It worked 🎉

**Closed by enzoferey** 2019-12-06 08:23 UTC
