### ISSUE TITLE
Error when extending a URL: assertNode could not find node

### ISSUE THREAD

**Issue by FWirtz** [enzoferey/slate-instant-replace#1] opened 2018-08-03 19:43 UTC
Hey @enzoferey,

nice job with this, exactly what I was looking for! 👏 👍 
I am trying to get your [url-example](https://github.com/enzoferey/slate-instant-replace/blob/master/examples/urls-example/src/Slate.js) running and everything works fine except for one thing:

When I type a URL like `http://go.co` it gets properly detected, tagged as an Inline and the node gets rendered. If I continue typing then - lets say the character `m` to finish the URL to be `http://go.com` I receive an error message in the console:

```
slate.es.js:7198 Uncaught Error: `Node.assertNode` could not find node with path or key: List [ 0, 2 ]
    at Document.Node.(:3000/anonymous function) [as assertNode] (http://localhost:3000/static/js/bundle.js:57490:13)
    at Document.splitNode (slate.es.js:6849)
    at Document.getFragmentAtRange (slate.es.js:5339)
    at Document.object.(:3000/anonymous function) [as getFragmentAtRange] (http://localhost:3000/static/js/bundle.js:51244:28)
    at Value.get$$1 (slate.es.js:12405)
    at getSelection (index.js:23)
    at getLastWordRec (index.js:31)
    at getLastWord (index.js:50)
    at Object.onKeyDown (index.js:87)
    at Stack$$1.run (slate.es.js:10253)
    at slate-react.es.js:4210
    at Change.call (slate.es.js:14204)
    at Editor.change (slate-react.es.js:4192)
    at Editor.onEvent (slate-react.es.js:4209)
    at Object._this.(:3000/anonymous function) [as onKeyDown] (http://localhost:3000/static/js/bundle.js:49360:23)
    at Content.onEvent (slate-react.es.js:2117)
    at _this.(:3000/anonymous function) (http://localhost:3000/static/js/bundle.js:47400:15)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at Object.invokeGuardedCallback (react-dom.development.js:187)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:201)
    at executeDispatch (react-dom.development.js:461)
    at executeDispatchesInOrder (react-dom.development.js:483)
    at executeDispatchesAndRelease (react-dom.development.js:581)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:592)
    at forEachAccumulated (react-dom.development.js:562)
    at runEventsInBatch (react-dom.development.js:723)
    at runExtractedEventsInBatch (react-dom.development.js:732)
    at handleTopLevel (react-dom.development.js:4476)
    at batchedUpdates$1 (react-dom.development.js:16659)
    at batchedUpdates (react-dom.development.js:2131)
    at dispatchEvent (react-dom.development.js:4555)
    at interactiveUpdates$1 (react-dom.development.js:16714)
    at interactiveUpdates (react-dom.development.js:2150)
    at dispatchInteractiveEvent (react-dom.development.js:4532)
```

I've been stuck at this point for half an hour now and came to conclude that this either is an issue with your extension or with Slate itself. I'll have a look at your code now, but I just got started with Slate today so that might not be that effective.

Would love it if you could have a look at this. Thanks! 😊

**Comment by FWirtz** [comment] 2018-08-03 20:04
**Update No 1**
the error seems to lie in `getSelection`:
```js
const getSelection = change => return change.value.fragment.text;
```

if I print the `change.value` right before crashing it looks like this:
```json
{
   "object":"value",
   "document":{
      "object":"document",
      "data":{

      },
      "nodes":[
         {
            "object":"block",
            "type":"paragraph",
            "isVoid":false,
            "data":{

            },
            "nodes":[
               {
                  "object":"text",
                  "leaves":[
                     {
                        "object":"leaf",
                        "text":"",
                        "marks":[

                        ]
                     }
                  ]
               },
               {
                  "object":"inline",
                  "type":"link",
                  "isVoid":false,
                  "data":{
                     "href":"http://google.co"
                  },
                  "nodes":[
                     {
                        "object":"text",
                        "leaves":[
                           {
                              "object":"leaf",
                              "text":"",
                              "marks":[

                              ]
                           }
                        ]
                     }
                  ]
               },
               {
                  "object":"text",
                  "leaves":[
                     {
                        "object":"leaf",
                        "text":"m",
                        "marks":[

                        ]
                     }
                  ]
               }
            ]
         }
      ]
   }
}
```

`.fragment.text` then naturally fails on that as there is no `fragment` child.
Will investigate further.

**Comment by enzoferey** [comment] 2018-08-03 20:21
Hello @FWirtz ! Thanks for the kind words, glad the pluing is useful for you 👍 

The error isn't related to the fragment thing you mentioned, fragment is taken from internal Slate data, not the value object.

Could you tell me which version of Slate are using ?

**Comment by FWirtz** [comment] 2018-08-03 20:41
hey @enzoferey thanks for the fast reply! still stuck with that and trying to go debug your sourcecode haha

running
slate:0.36.1
slate-react:0.14.2
slate-instant-replace:0.1.7

**Comment by enzoferey** [comment] 2018-08-03 21:01
Thanks @FWirtz, I was finishing some stuff IRL, I'm looking at it right now.

**Comment by FWirtz** [comment] 2018-08-03 21:05
wow cool thanks so much! esp. given the fact that it's 11pm on a Friday night in madrid as well haha ❤️

**Comment by enzoferey** [comment] 2018-08-03 21:07
This is important for me ;) 

I can indeed reproduce the error, I will keep you updated.

**Comment by FWirtz** [comment] 2018-08-03 21:14
awesome thank you SO SO SO much!
I've spent all my afternoon trying to figure that out and really started to loose faith in my react skills <.<

**Comment by enzoferey** [comment] 2018-08-03 21:32
Located the error, not sure how to fix it yet. I developed the plugin with slate 0.34.2 (working example here https://codesandbox.io/s/322jv8rxkp) and when using newer version it crashes.

If this is urgent for you, downgrade to 0.34.2 and luckily you won't have other issues with other libs you are using. I will work on a fix asap.

**Comment by enzoferey** [comment] 2018-08-03 22:14
v0.1.8 published #https://github.com/enzoferey/slate-instant-replace/commit/e01d5774c1e93faad86808379c35fded7ad24cc3 

By the way I had a peerDependency on ^0.34.2 set up, and 0.35.0 was marked as a breaking upgrade by the Slate guys, to it made a lot of sense 😄 

Thank you for pointing it out, I'll close the issue whenever you confirm everything is working.

**Comment by FWirtz** [comment] 2018-08-04 08:03
@enzoferey AWESOME! Just tested it, works like a charm.

Just fyi the slate logger says:
```
The `value.focusOffset` property is deprecated, please use `selection.focus.offset` instead.
```

probably because of this:
https://github.com/enzoferey/slate-instant-replace/blob/e01d5774c1e93faad86808379c35fded7ad24cc3/lib/index.js#L32

you might want to change that as well.
but a warning is not an error, so major win here! 👍 

Thanks again!

**Comment by enzoferey** [comment] 2018-08-04 09:38
Good morning @FWirtz !

Slate upgraded to 0.37.0 since last night, bringing those deprecated messages hahaha

There is also:

`The `Change.extend` method is deprecated, please use `Change.moveFocusForward` instead. `

It seems that decision is here to stay, but I will wait a little bit before upgrading the references so I can fix any new possible API introduced in their next commits, they have backwards compability right now ;)

Closing the issue. Thanks !

**Closed** 2018-08-04 09:39 UTC

**Comment by FWirtz** [comment] 2018-08-06 14:26
hahaha no way sorry didn't notice that.
No worries, lgtm so far! Thanks for fixing it!
